INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Ana', 'Gómez', 'Tarjeta de crédito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Luis', 'Pérez', 'PayPal');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Carlos', 'Martínez', 'Transferencia');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('María', 'López', 'Efectivo');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Javier', 'Ortega', 'Tarjeta de débito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Sofía', 'Ramírez', 'Tarjeta de crédito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Andrés', 'Méndez', 'PayPal');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Laura', 'Jiménez', 'Efectivo');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Pedro', 'Castillo', 'Transferencia');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Valeria', 'Ríos', 'Tarjeta de débito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Fernando', 'Navarro', 'PayPal');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Diana', 'Morales', 'Tarjeta de crédito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Martín', 'Cano', 'Efectivo');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Carmen', 'Fuentes', 'Transferencia');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Héctor', 'Vargas', 'PayPal');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Isabel', 'Acosta', 'Tarjeta de débito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Raúl', 'Santos', 'Efectivo');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Lucía', 'Herrera', 'Tarjeta de crédito');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Esteban', 'Domínguez', 'PayPal');
INSERT INTO customers (first_name, last_name, payment_method) VALUES ('Paola', 'Delgado', 'Transferencia');